# Real host ip
ansible_host: 185.196.196.66

# Private host ip
host_private_ip: 10.200.0.6

# SSH user which connect to servers
ansible_user: adminroot

# Uncomment for Latest DEB-based distros (Ubuntu, Debian)
ansible_python_interpreter: /usr/bin/python3